kind: Service
apiVersion: v1
metadata:
  name: mongo
  labels:
    app: mongo
  namespace: connectwe-ns
spec:
  selector:
    app: connectwe-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
